# Generated by Django 5.2.14 on 2026-05-16 17:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failure', 'Failure'), ('cancelled', 'Cancelled'), ('skipped', 'Skipped')], max_length=32)),
                ('branch', models.CharField(max_length=255)),
                ('commit_sha', models.CharField(max_length=64)),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Build duration in seconds, when known.', null=True)),
                ('raw_payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_events', to='organizations.project')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['project', 'created_at'], name='ingestion_b_project_e02d34_idx'), models.Index(fields=['status', 'branch'], name='ingestion_b_status_e51c4c_idx')],
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'GitLab')], max_length=32)),
                ('delivery_id', models.CharField(max_length=255)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_deliveries', to='organizations.project')),
            ],
            options={
                'ordering': ('-received_at',),
                'constraints': [models.UniqueConstraint(fields=('provider', 'delivery_id'), name='ingestion_webhookdelivery_provider_delivery_id_unique')],
            },
        ),
    ]
