# Generated by Django 5.2.14 on 2026-05-20 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildevent',
            name='webhook_delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='build_events', to='ingestion.webhookdelivery'),
        ),
        migrations.AddField(
            model_name='webhookdelivery',
            name='raw_payload',
            field=models.JSONField(default=dict),
        ),
    ]
