# Generated by Django 5.2.14 on 2026-05-20 15:11

import apps.organizations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='webhook_secret',
            field=models.CharField(default=apps.organizations.models.generate_webhook_secret, help_text='Shared secret for webhook HMAC verification (GitHub) or token (GitLab).', max_length=64),
        ),
    ]
